# Generated by Django 4.2.7 on 2024-01-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow_delete_profile_user_user_to_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_to_follow',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
