# Generated by Django 4.2.7 on 2024-01-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='following',
        ),
    ]
