# Generated by Django 4.2.7 on 2024-01-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'likes')},
        ),
    ]
