# Generated by Django 4.2.7 on 2024-01-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_post_likes_alter_post_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('likes', 'user'), name='unique likes'),
        ),
    ]
