# Generated by Django 4.2.7 on 2024-02-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_remove_post_unique_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
